spring.application.name=triage

# JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Seguridad basica
#spring.security.user.name=triage_user
#spring.security.user.password=123456

# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/triage
spring.datasource.username=triage_user
spring.datasource.password= 123456
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

server.error.include-message=always

# Groq API
ia.habilitada=true
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
ia.api.model=llama-3.1-8b-instant

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000
